name: Cache Rust
description: Cache Cargo caches and target directories

inputs:
  target-dir:
    description: Path to the Cargo target directory
    default: target/
  cache-key:
    description: Cache key to distinguish this invocation from other uses of the action in the same repo
    default: default

runs:
  using: composite
  steps:
    - name: Detect the installed Rust version
      id: rustc
      run: echo "version=$(rustc -V)" >> "${GITHUB_OUTPUT}"
      shell: bash

    - name: Cache Cargo's registry cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry/cache
        key: cargo-registry-cache-${{ inputs.cache-key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-cache-${{ inputs.cache-key }}-

    - name: Cache Cargo's registry index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry/index
        key: cargo-registry-index-${{ inputs.cache-key }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-index-${{ inputs.cache-key }}-

    - name: Cache Cargo's target directory
      uses: actions/cache@v3
      with:
        path: "${{ inputs.target-dir }}-${{ inputs.cache-key }}-"
        key: cargo-build-${{ inputs.cache-key }}-${{ steps.rustc.outputs.version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-build-${{ inputs.cache-key }}-${{ steps.rustc.outputs.version }}-
