# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

---
name: "Use Ferrocene"
description: "Installs CriticalUp. Requires a criticalup.toml configuration. Intended for Ferrocene packages installation"
inputs:
  token:
    description: The CriticalUp token to use (use a GHA Secret)
    required: true
  uninstall-rustup:
    description: "If `rustup` should be uninstalled as well, ensuring only Ferrocene can be used (conflicts with `toolchain-link: true`)"
    required: false
    default: "false"
  toolchain-link:
    description: "If a `rustup` toolchain should be configured, allowing, for example `cargo +ferrocene build` (conflicts with `uninstall-rustup: true`)"
    required: false
    default: "true"
  cache-toolchain:
    description: "If the Ferrocene toolchain should be cached (only available on Linux)"
    required: false
    default: "true"
  remove-auth:
    description: "If the CriticalUp authentication should be removed after installing the toolchain. This should be `true` if caching is enabled."
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Check for conflicting inputs
      if: ${{ inputs.uninstall-rustup == 'true' && inputs.toolchain-link == 'true' }}
      shell: bash
      run: exit 1

    - name: Remove Rust
      if: ${{ inputs.uninstall-rustup == 'true' }}
      shell: bash
      run: |
        rm -rf ~/.rustup
        rm -rf ~/.cargo

    - name: Install criticalup
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/latest/download/criticalup-installer.sh | sh

    - name: Cache Ferrocene toolchain
      id: cache-criticalup
      if: ${{ runner.os == 'Linux' && inputs.cache-criticalup == 'true' }}
      uses: actions/cache@v5
      with:
        path: ~/.local/share/criticalup/
        key: ${{ runner.os }}-criticalup-${{ hashFiles('**/criticalup.toml') }}

    - name: Install Ferrocene toolchain
      if: ${{ steps.cache-criticalup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        criticalup auth set ${{ inputs.token }}
        criticalup install

    - name: Remove CriticalUp authentication (to avoid caching it)
      if: ${{ inputs.remove-auth == 'true' }}
      shell: bash
      run: criticalup auth remove

    - name: Link `ferrocene` toolchain in `rustup`
      if: ${{ inputs.toolchain-link == 'true' }}
      shell: bash
      run: |
        criticalup link create
        rustup default ferrocene

    - name: Output installed toolchains
      if: ${{ inputs.uninstall-rustup == 'false' }}
      shell: bash
      run: echo $(rustup toolchain list -v)
