# SPDX-FileCopyrightText: The Ferrocene Developers
# SPDX-License-Identifier: MIT OR Apache-2.0

---

name: "Use Ferrocene"
description: "Use Ferrocene"
inputs:
  token:
    description: The CriticalUp token to use (use a GHA Secret)
    required: true
  uninstall-rustup:
    description: "If `rustup` should be uninstalled as well, ensuring only Ferrocene can be used (conflicts with `toolchain-link: true`)"
    required: false
    default: "false"
  toolchain-link:
    description: "If a `rustup` toolchain should be configured, allowing, for example `cargo +ferrocene build` (conflicts with `uninstall-rustup: true`)"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Remove Rust
      if: ${{ inputs.uninstall-rustup == 'true' }}
      shell: bash
      run: |
        rm -rf ~/.rustup
        rm -rf ~/.cargo

    - name: Prepares criticalup manifest
      shell: bash
      run: |
        cat <<- EOF > criticalup.toml
          manifest-version = 1

          [products.ferrocene]
          release = "stable-25.05.0"
          packages = [
              "cargo-\${rustc-host}",
              "rustc-\${rustc-host}",
              "rust-std-\${rustc-host}",
          ]
        EOF

    - name: Install Ferrocene
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/ferrocene/criticalup/releases/latest/download/criticalup-installer.sh | sh
        criticalup auth set ${{ inputs.token }}
        criticalup install
    
    - name: Link `ferrocene` toolchain in `rustup`
      if: ${{ inputs.toolchain-link == 'true' }}
      shell: bash
      run: |
        criticalup link create
        
    - name: Output installed toolchains
      shell: bash
      run: echo $(rustup toolchain list -v)

    - name: Output cargo version
      shell: bash
      run: echo $(cargo -V)
