---

name: mdBook to GitHub Pages
on:
  workflow_call:
    inputs:
      cname:
        type: string
        required: true
      path:
        type: string
        default: .
      version:
        type: string
        default: 0.4.14
      cache-target-directory:
        type: boolean
        default: false

jobs:
  main:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Download mdBook ${{ inputs.version }}
        run: |
          mkdir -p /tmp/mdbook
          curl -Lo- https://github.com/rust-lang/mdBook/releases/download/v${{ inputs.version }}/mdbook-v${{ inputs.version }}-x86_64-unknown-linux-gnu.tar.gz | tar -C /tmp/mdbook -xzv

      - uses: ferrous-systems/shared-github-actions/cache-rust@main
        with:
          target-dir: /tmp/target
        if: inputs.cache-target-directory

      - name: Build the contents of the book
        run: /tmp/mdbook/mdbook build ${{ inputs.path }} -d /tmp/book
        env:
          CARGO_TARGET_DIR: /tmp/target

      - name: Deploy to GitHub Pages
        uses: ferrous-systems/shared-github-actions/github-pages@main
        with:
          path: /tmp/book
          cname: ${{ inputs.cname }}
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/main'
